name = "rmbg-redirect"
main = "index.js"
compatibility_date = "2024-01-01"
account_id = "f5f3956578d118a6398a891c3aca2605"

routes = [
  { pattern = "rmbg.skyqing.online", zone_name = "skyqing.online" }
]
